// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/database/entities/collection_entity.dart';
import 'core/database/entities/cookie_jar_entity.dart';
import 'core/database/entities/environment_entity.dart';
import 'core/database/entities/history_entity.dart';
import 'core/database/entities/node_entity.dart';
import 'core/database/entities/websocket_message_entity.dart';
import 'core/database/entities/websocket_session_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5570044280377796997),
    name: 'CollectionEntity',
    lastPropertyId: const obx_int.IdUid(10, 8467056271953228457),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6486425281478253977),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2960743598504227965),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5499281950486062944),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7138322006164209844),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5297698899744803918),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6656238608472947287),
        name: 'path',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8033670793440821754),
        name: 'selectedEnvId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7087347246569023560),
        name: 'selectedJarId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 788942307543725488),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4307797785585676034),
        name: 'headers',
        type: 13,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8467056271953228457),
        name: 'auth',
        type: 13,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6807675035617574111),
    name: 'CookieJarEntity',
    lastPropertyId: const obx_int.IdUid(5, 7937011021246497870),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5079002510888662760),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 340756250549908657),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 7650355114837898531),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7303374824062610558),
        name: 'collectionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 8462402866758057927),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6395110673907222028),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7937011021246497870),
        name: 'cookies',
        type: 13,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1471373301515201373),
    name: 'EnvironmentEntity',
    lastPropertyId: const obx_int.IdUid(8, 130252413565881839),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7685163183774314120),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5396379916154038684),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 2854976308552333857),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 193157572129409390),
        name: 'collectionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 8803392059261011301),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7373948345339544201),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8152118543036021101),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2933294306362652552),
        name: 'isShared',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7729579069482975992),
        name: 'isGlobal',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 130252413565881839),
        name: 'variables',
        type: 13,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1589747562368478009),
    name: 'HistoryEntity',
    lastPropertyId: const obx_int.IdUid(16, 4266804411084962393),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6030359543847235677),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2761776864004442863),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 3462365657544881050),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2735869530966272211),
        name: 'requestId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 1646315374615310354),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8484616415643598760),
        name: 'collectionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 7175751629835237551),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6926532615922990295),
        name: 'statusCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5436099799754281680),
        name: 'statusMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2983880965151108379),
        name: 'executeAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8852569114509765785),
        name: 'durationMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8964671163572543984),
        name: 'protocolVersion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2331713029493195076),
        name: 'headers',
        type: 13,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4247056657780144915),
        name: 'bodyBytes',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3976138900755334436),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6596622485786268593),
        name: 'bodyType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6068302863648199366),
        name: 'errorMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 1102702881259066499),
        name: 'redirectUrls',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4266804411084962393),
        name: 'finalUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7045792345788763009),
    name: 'NodeEntity',
    lastPropertyId: const obx_int.IdUid(20, 5331732017826239985),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2047262070393388639),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6286778368687934553),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 7892538428914304626),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2329711183292280207),
        name: 'collectionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 560293841386183381),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7894971316445150149),
        name: 'parentId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(11, 4160581124254408981),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 149369836196794806),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4060323689753227892),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5131235605107673215),
        name: 'method',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8405523466970509051),
        name: 'requestType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7127514546808144944),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6983526132492250791),
        name: 'headers',
        type: 13,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1714112601978566747),
        name: 'auth',
        type: 13,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2590901113599482516),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1895649804831126583),
        name: 'queryParameters',
        type: 13,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8051979031673356492),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8085760238601813563),
        name: 'bodyType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 935236628824102684),
        name: 'scripts',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 4169932291082340768),
        name: 'historyId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 1975431877183496628),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 4298147165201441639),
        name: 'variables',
        type: 13,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 5331732017826239985),
        name: 'statusCode',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 2191741604637846510),
    name: 'WebSocketMessageEntity',
    lastPropertyId: const obx_int.IdUid(7, 4539365365973080292),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1411010204642707860),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5884806950962707737),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(12, 7206451815060611991),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 154126830914637022),
        name: 'requestId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(13, 5989454394142172892),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8667520379085163368),
        name: 'sessionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 5295047086636247981),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5195730381565090724),
        name: 'isSent',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1272083227294824898),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4539365365973080292),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 8265781918139091118),
    name: 'WebSocketSessionEntity',
    lastPropertyId: const obx_int.IdUid(7, 2104764757953553458),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 484564671969202180),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8691049316254946099),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(15, 1617644963776940922),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5335857738356971623),
        name: 'collectionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(16, 1429828016548327954),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7772938801944439383),
        name: 'requestId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(17, 5170331141364777766),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8434061401330245840),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6551373979204620189),
        name: 'startTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2104764757953553458),
        name: 'endTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 8265781918139091118),
    lastIndexId: const obx_int.IdUid(17, 5170331141364777766),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CollectionEntity: obx_int.EntityDefinition<CollectionEntity>(
      model: _entities[0],
      toOneRelations: (CollectionEntity object) => [],
      toManyRelations: (CollectionEntity object) => {},
      getId: (CollectionEntity object) => object.id,
      setId: (CollectionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CollectionEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final nameOffset = fbb.writeString(object.name);
        final typeOffset = fbb.writeString(object.type);
        final pathOffset = object.path == null
            ? null
            : fbb.writeString(object.path!);
        final selectedEnvIdOffset = object.selectedEnvId == null
            ? null
            : fbb.writeString(object.selectedEnvId!);
        final selectedJarIdOffset = object.selectedJarId == null
            ? null
            : fbb.writeString(object.selectedJarId!);
        final descriptionOffset = fbb.writeString(object.description);
        final headersOffset = object.headers == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.headers!));
        final authOffset = object.auth == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.auth!));
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, pathOffset);
        fbb.addOffset(5, selectedEnvIdOffset);
        fbb.addOffset(6, selectedJarIdOffset);
        fbb.addOffset(7, descriptionOffset);
        fbb.addOffset(8, headersOffset);
        fbb.addOffset(9, authOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final pathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final selectedEnvIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final selectedJarIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final headersParam = obx_int.flexBufferToListOfMaps(
          buffer,
          rootOffset,
          20,
        );
        final authParam = obx_int.flexBufferToMap(buffer, rootOffset, 22);
        final object = CollectionEntity(
          id: idParam,
          uid: uidParam,
          name: nameParam,
          type: typeParam,
          path: pathParam,
          selectedEnvId: selectedEnvIdParam,
          selectedJarId: selectedJarIdParam,
          description: descriptionParam,
          headers: headersParam,
          auth: authParam,
        );

        return object;
      },
    ),
    CookieJarEntity: obx_int.EntityDefinition<CookieJarEntity>(
      model: _entities[1],
      toOneRelations: (CookieJarEntity object) => [],
      toManyRelations: (CookieJarEntity object) => {},
      getId: (CookieJarEntity object) => object.id,
      setId: (CookieJarEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CookieJarEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final collectionIdOffset = fbb.writeString(object.collectionId);
        final nameOffset = fbb.writeString(object.name);
        final cookiesOffset = object.cookies == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.cookies!));
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, collectionIdOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, cookiesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final collectionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final cookiesParam = obx_int.flexBufferToListOfMaps(
          buffer,
          rootOffset,
          12,
        );
        final object = CookieJarEntity(
          id: idParam,
          uid: uidParam,
          collectionId: collectionIdParam,
          name: nameParam,
          cookies: cookiesParam,
        );

        return object;
      },
    ),
    EnvironmentEntity: obx_int.EntityDefinition<EnvironmentEntity>(
      model: _entities[2],
      toOneRelations: (EnvironmentEntity object) => [],
      toManyRelations: (EnvironmentEntity object) => {},
      getId: (EnvironmentEntity object) => object.id,
      setId: (EnvironmentEntity object, int id) {
        object.id = id;
      },
      objectToFB: (EnvironmentEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final collectionIdOffset = fbb.writeString(object.collectionId);
        final nameOffset = fbb.writeString(object.name);
        final variablesOffset = object.variables == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.variables!));
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, collectionIdOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addInt64(4, object.colorValue);
        fbb.addBool(5, object.isShared);
        fbb.addBool(6, object.isGlobal);
        fbb.addOffset(7, variablesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final collectionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final colorValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final isSharedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final isGlobalParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final variablesParam = obx_int.flexBufferToListOfMaps(
          buffer,
          rootOffset,
          18,
        );
        final object = EnvironmentEntity(
          id: idParam,
          uid: uidParam,
          collectionId: collectionIdParam,
          name: nameParam,
          colorValue: colorValueParam,
          isShared: isSharedParam,
          isGlobal: isGlobalParam,
          variables: variablesParam,
        );

        return object;
      },
    ),
    HistoryEntity: obx_int.EntityDefinition<HistoryEntity>(
      model: _entities[3],
      toOneRelations: (HistoryEntity object) => [],
      toManyRelations: (HistoryEntity object) => {},
      getId: (HistoryEntity object) => object.id,
      setId: (HistoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (HistoryEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final requestIdOffset = fbb.writeString(object.requestId);
        final collectionIdOffset = fbb.writeString(object.collectionId);
        final statusMessageOffset = fbb.writeString(object.statusMessage);
        final protocolVersionOffset = fbb.writeString(object.protocolVersion);
        final headersOffset = object.headers == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.headers!));
        final bodyBytesOffset = fbb.writeListInt8(object.bodyBytes);
        final bodyOffset = fbb.writeString(object.body);
        final bodyTypeOffset = object.bodyType == null
            ? null
            : fbb.writeString(object.bodyType!);
        final errorMessageOffset = object.errorMessage == null
            ? null
            : fbb.writeString(object.errorMessage!);
        final redirectUrlsOffset = object.redirectUrls == null
            ? null
            : fbb.writeList(
                object.redirectUrls!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        final finalUrlOffset = object.finalUrl == null
            ? null
            : fbb.writeString(object.finalUrl!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, requestIdOffset);
        fbb.addOffset(3, collectionIdOffset);
        fbb.addInt64(4, object.statusCode);
        fbb.addOffset(5, statusMessageOffset);
        fbb.addInt64(6, object.executeAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.durationMs);
        fbb.addOffset(8, protocolVersionOffset);
        fbb.addOffset(9, headersOffset);
        fbb.addOffset(10, bodyBytesOffset);
        fbb.addOffset(11, bodyOffset);
        fbb.addOffset(12, bodyTypeOffset);
        fbb.addOffset(13, errorMessageOffset);
        fbb.addOffset(14, redirectUrlsOffset);
        fbb.addOffset(15, finalUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final requestIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final collectionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final statusCodeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final statusMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final executeAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final durationMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final protocolVersionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final headersParam = obx_int.flexBufferToList(buffer, rootOffset, 22);
        final bodyBytesParam =
            const fb.Uint8ListReader(
                  lazy: false,
                ).vTableGet(buffer, rootOffset, 24, Uint8List(0))
                as Uint8List;
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final bodyTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final errorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final redirectUrlsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final finalUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final object = HistoryEntity(
          id: idParam,
          uid: uidParam,
          requestId: requestIdParam,
          collectionId: collectionIdParam,
          statusCode: statusCodeParam,
          statusMessage: statusMessageParam,
          executeAt: executeAtParam,
          durationMs: durationMsParam,
          protocolVersion: protocolVersionParam,
          headers: headersParam,
          bodyBytes: bodyBytesParam,
          body: bodyParam,
          bodyType: bodyTypeParam,
          errorMessage: errorMessageParam,
          redirectUrls: redirectUrlsParam,
          finalUrl: finalUrlParam,
        );

        return object;
      },
    ),
    NodeEntity: obx_int.EntityDefinition<NodeEntity>(
      model: _entities[4],
      toOneRelations: (NodeEntity object) => [],
      toManyRelations: (NodeEntity object) => {},
      getId: (NodeEntity object) => object.id,
      setId: (NodeEntity object, int id) {
        object.id = id;
      },
      objectToFB: (NodeEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final collectionIdOffset = fbb.writeString(object.collectionId);
        final parentIdOffset = object.parentId == null
            ? null
            : fbb.writeString(object.parentId!);
        final nameOffset = fbb.writeString(object.name);
        final typeOffset = fbb.writeString(object.type);
        final methodOffset = object.method == null
            ? null
            : fbb.writeString(object.method!);
        final requestTypeOffset = object.requestType == null
            ? null
            : fbb.writeString(object.requestType!);
        final headersOffset = object.headers == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.headers!));
        final authOffset = object.auth == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.auth!));
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final queryParametersOffset = object.queryParameters == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.queryParameters!));
        final bodyOffset = object.body == null
            ? null
            : fbb.writeString(object.body!);
        final bodyTypeOffset = object.bodyType == null
            ? null
            : fbb.writeString(object.bodyType!);
        final scriptsOffset = object.scripts == null
            ? null
            : fbb.writeString(object.scripts!);
        final historyIdOffset = object.historyId == null
            ? null
            : fbb.writeString(object.historyId!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final variablesOffset = object.variables == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.variables!));
        fbb.startTable(21);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, collectionIdOffset);
        fbb.addOffset(3, parentIdOffset);
        fbb.addOffset(4, nameOffset);
        fbb.addOffset(5, typeOffset);
        fbb.addOffset(6, methodOffset);
        fbb.addOffset(7, requestTypeOffset);
        fbb.addInt64(8, object.sortOrder);
        fbb.addOffset(9, headersOffset);
        fbb.addOffset(10, authOffset);
        fbb.addOffset(11, urlOffset);
        fbb.addOffset(12, queryParametersOffset);
        fbb.addOffset(13, bodyOffset);
        fbb.addOffset(14, bodyTypeOffset);
        fbb.addOffset(15, scriptsOffset);
        fbb.addOffset(16, historyIdOffset);
        fbb.addOffset(17, descriptionOffset);
        fbb.addOffset(18, variablesOffset);
        fbb.addInt64(19, object.statusCode);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final collectionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final parentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final methodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final requestTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final headersParam = obx_int.flexBufferToListOfMaps(
          buffer,
          rootOffset,
          22,
        );
        final authParam = obx_int.flexBufferToMap(buffer, rootOffset, 24);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final queryParametersParam = obx_int.flexBufferToListOfMaps(
          buffer,
          rootOffset,
          28,
        );
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final bodyTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final scriptsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final historyIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final variablesParam = obx_int.flexBufferToListOfMaps(
          buffer,
          rootOffset,
          40,
        );
        final statusCodeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          42,
        );
        final object = NodeEntity(
          id: idParam,
          uid: uidParam,
          collectionId: collectionIdParam,
          parentId: parentIdParam,
          name: nameParam,
          type: typeParam,
          method: methodParam,
          requestType: requestTypeParam,
          sortOrder: sortOrderParam,
          headers: headersParam,
          auth: authParam,
          url: urlParam,
          queryParameters: queryParametersParam,
          body: bodyParam,
          bodyType: bodyTypeParam,
          scripts: scriptsParam,
          historyId: historyIdParam,
          description: descriptionParam,
          variables: variablesParam,
          statusCode: statusCodeParam,
        );

        return object;
      },
    ),
    WebSocketMessageEntity: obx_int.EntityDefinition<WebSocketMessageEntity>(
      model: _entities[5],
      toOneRelations: (WebSocketMessageEntity object) => [],
      toManyRelations: (WebSocketMessageEntity object) => {},
      getId: (WebSocketMessageEntity object) => object.id,
      setId: (WebSocketMessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (WebSocketMessageEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final requestIdOffset = fbb.writeString(object.requestId);
        final sessionIdOffset = object.sessionId == null
            ? null
            : fbb.writeString(object.sessionId!);
        final messageOffset = fbb.writeString(object.message);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, requestIdOffset);
        fbb.addOffset(3, sessionIdOffset);
        fbb.addBool(4, object.isSent);
        fbb.addOffset(5, messageOffset);
        fbb.addInt64(6, object.timestamp.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final requestIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final isSentParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = WebSocketMessageEntity(
          id: idParam,
          uid: uidParam,
          requestId: requestIdParam,
          sessionId: sessionIdParam,
          isSent: isSentParam,
          message: messageParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
    WebSocketSessionEntity: obx_int.EntityDefinition<WebSocketSessionEntity>(
      model: _entities[6],
      toOneRelations: (WebSocketSessionEntity object) => [],
      toManyRelations: (WebSocketSessionEntity object) => {},
      getId: (WebSocketSessionEntity object) => object.id,
      setId: (WebSocketSessionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (WebSocketSessionEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final collectionIdOffset = fbb.writeString(object.collectionId);
        final requestIdOffset = fbb.writeString(object.requestId);
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, collectionIdOffset);
        fbb.addOffset(3, requestIdOffset);
        fbb.addOffset(4, urlOffset);
        fbb.addInt64(5, object.startTime.millisecondsSinceEpoch);
        fbb.addInt64(6, object.endTime?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final collectionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final requestIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final startTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final endTimeParam = endTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endTimeValue);
        final object = WebSocketSessionEntity(
          id: idParam,
          uid: uidParam,
          collectionId: collectionIdParam,
          requestId: requestIdParam,
          url: urlParam,
          startTime: startTimeParam,
          endTime: endTimeParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CollectionEntity] entity fields to define ObjectBox queries.
class CollectionEntity_ {
  /// See [CollectionEntity.id].
  static final id = obx.QueryIntegerProperty<CollectionEntity>(
    _entities[0].properties[0],
  );

  /// See [CollectionEntity.uid].
  static final uid = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[1],
  );

  /// See [CollectionEntity.name].
  static final name = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[2],
  );

  /// See [CollectionEntity.type].
  static final type = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[3],
  );

  /// See [CollectionEntity.path].
  static final path = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[4],
  );

  /// See [CollectionEntity.selectedEnvId].
  static final selectedEnvId = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[5],
  );

  /// See [CollectionEntity.selectedJarId].
  static final selectedJarId = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[6],
  );

  /// See [CollectionEntity.description].
  static final description = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[7],
  );
}

/// [CookieJarEntity] entity fields to define ObjectBox queries.
class CookieJarEntity_ {
  /// See [CookieJarEntity.id].
  static final id = obx.QueryIntegerProperty<CookieJarEntity>(
    _entities[1].properties[0],
  );

  /// See [CookieJarEntity.uid].
  static final uid = obx.QueryStringProperty<CookieJarEntity>(
    _entities[1].properties[1],
  );

  /// See [CookieJarEntity.collectionId].
  static final collectionId = obx.QueryStringProperty<CookieJarEntity>(
    _entities[1].properties[2],
  );

  /// See [CookieJarEntity.name].
  static final name = obx.QueryStringProperty<CookieJarEntity>(
    _entities[1].properties[3],
  );
}

/// [EnvironmentEntity] entity fields to define ObjectBox queries.
class EnvironmentEntity_ {
  /// See [EnvironmentEntity.id].
  static final id = obx.QueryIntegerProperty<EnvironmentEntity>(
    _entities[2].properties[0],
  );

  /// See [EnvironmentEntity.uid].
  static final uid = obx.QueryStringProperty<EnvironmentEntity>(
    _entities[2].properties[1],
  );

  /// See [EnvironmentEntity.collectionId].
  static final collectionId = obx.QueryStringProperty<EnvironmentEntity>(
    _entities[2].properties[2],
  );

  /// See [EnvironmentEntity.name].
  static final name = obx.QueryStringProperty<EnvironmentEntity>(
    _entities[2].properties[3],
  );

  /// See [EnvironmentEntity.colorValue].
  static final colorValue = obx.QueryIntegerProperty<EnvironmentEntity>(
    _entities[2].properties[4],
  );

  /// See [EnvironmentEntity.isShared].
  static final isShared = obx.QueryBooleanProperty<EnvironmentEntity>(
    _entities[2].properties[5],
  );

  /// See [EnvironmentEntity.isGlobal].
  static final isGlobal = obx.QueryBooleanProperty<EnvironmentEntity>(
    _entities[2].properties[6],
  );
}

/// [HistoryEntity] entity fields to define ObjectBox queries.
class HistoryEntity_ {
  /// See [HistoryEntity.id].
  static final id = obx.QueryIntegerProperty<HistoryEntity>(
    _entities[3].properties[0],
  );

  /// See [HistoryEntity.uid].
  static final uid = obx.QueryStringProperty<HistoryEntity>(
    _entities[3].properties[1],
  );

  /// See [HistoryEntity.requestId].
  static final requestId = obx.QueryStringProperty<HistoryEntity>(
    _entities[3].properties[2],
  );

  /// See [HistoryEntity.collectionId].
  static final collectionId = obx.QueryStringProperty<HistoryEntity>(
    _entities[3].properties[3],
  );

  /// See [HistoryEntity.statusCode].
  static final statusCode = obx.QueryIntegerProperty<HistoryEntity>(
    _entities[3].properties[4],
  );

  /// See [HistoryEntity.statusMessage].
  static final statusMessage = obx.QueryStringProperty<HistoryEntity>(
    _entities[3].properties[5],
  );

  /// See [HistoryEntity.executeAt].
  static final executeAt = obx.QueryDateProperty<HistoryEntity>(
    _entities[3].properties[6],
  );

  /// See [HistoryEntity.durationMs].
  static final durationMs = obx.QueryIntegerProperty<HistoryEntity>(
    _entities[3].properties[7],
  );

  /// See [HistoryEntity.protocolVersion].
  static final protocolVersion = obx.QueryStringProperty<HistoryEntity>(
    _entities[3].properties[8],
  );

  /// See [HistoryEntity.bodyBytes].
  static final bodyBytes = obx.QueryByteVectorProperty<HistoryEntity>(
    _entities[3].properties[10],
  );

  /// See [HistoryEntity.body].
  static final body = obx.QueryStringProperty<HistoryEntity>(
    _entities[3].properties[11],
  );

  /// See [HistoryEntity.bodyType].
  static final bodyType = obx.QueryStringProperty<HistoryEntity>(
    _entities[3].properties[12],
  );

  /// See [HistoryEntity.errorMessage].
  static final errorMessage = obx.QueryStringProperty<HistoryEntity>(
    _entities[3].properties[13],
  );

  /// See [HistoryEntity.redirectUrls].
  static final redirectUrls = obx.QueryStringVectorProperty<HistoryEntity>(
    _entities[3].properties[14],
  );

  /// See [HistoryEntity.finalUrl].
  static final finalUrl = obx.QueryStringProperty<HistoryEntity>(
    _entities[3].properties[15],
  );
}

/// [NodeEntity] entity fields to define ObjectBox queries.
class NodeEntity_ {
  /// See [NodeEntity.id].
  static final id = obx.QueryIntegerProperty<NodeEntity>(
    _entities[4].properties[0],
  );

  /// See [NodeEntity.uid].
  static final uid = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[1],
  );

  /// See [NodeEntity.collectionId].
  static final collectionId = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[2],
  );

  /// See [NodeEntity.parentId].
  static final parentId = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[3],
  );

  /// See [NodeEntity.name].
  static final name = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[4],
  );

  /// See [NodeEntity.type].
  static final type = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[5],
  );

  /// See [NodeEntity.method].
  static final method = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[6],
  );

  /// See [NodeEntity.requestType].
  static final requestType = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[7],
  );

  /// See [NodeEntity.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<NodeEntity>(
    _entities[4].properties[8],
  );

  /// See [NodeEntity.url].
  static final url = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[11],
  );

  /// See [NodeEntity.body].
  static final body = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[13],
  );

  /// See [NodeEntity.bodyType].
  static final bodyType = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[14],
  );

  /// See [NodeEntity.scripts].
  static final scripts = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[15],
  );

  /// See [NodeEntity.historyId].
  static final historyId = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[16],
  );

  /// See [NodeEntity.description].
  static final description = obx.QueryStringProperty<NodeEntity>(
    _entities[4].properties[17],
  );

  /// See [NodeEntity.statusCode].
  static final statusCode = obx.QueryIntegerProperty<NodeEntity>(
    _entities[4].properties[19],
  );
}

/// [WebSocketMessageEntity] entity fields to define ObjectBox queries.
class WebSocketMessageEntity_ {
  /// See [WebSocketMessageEntity.id].
  static final id = obx.QueryIntegerProperty<WebSocketMessageEntity>(
    _entities[5].properties[0],
  );

  /// See [WebSocketMessageEntity.uid].
  static final uid = obx.QueryStringProperty<WebSocketMessageEntity>(
    _entities[5].properties[1],
  );

  /// See [WebSocketMessageEntity.requestId].
  static final requestId = obx.QueryStringProperty<WebSocketMessageEntity>(
    _entities[5].properties[2],
  );

  /// See [WebSocketMessageEntity.sessionId].
  static final sessionId = obx.QueryStringProperty<WebSocketMessageEntity>(
    _entities[5].properties[3],
  );

  /// See [WebSocketMessageEntity.isSent].
  static final isSent = obx.QueryBooleanProperty<WebSocketMessageEntity>(
    _entities[5].properties[4],
  );

  /// See [WebSocketMessageEntity.message].
  static final message = obx.QueryStringProperty<WebSocketMessageEntity>(
    _entities[5].properties[5],
  );

  /// See [WebSocketMessageEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<WebSocketMessageEntity>(
    _entities[5].properties[6],
  );
}

/// [WebSocketSessionEntity] entity fields to define ObjectBox queries.
class WebSocketSessionEntity_ {
  /// See [WebSocketSessionEntity.id].
  static final id = obx.QueryIntegerProperty<WebSocketSessionEntity>(
    _entities[6].properties[0],
  );

  /// See [WebSocketSessionEntity.uid].
  static final uid = obx.QueryStringProperty<WebSocketSessionEntity>(
    _entities[6].properties[1],
  );

  /// See [WebSocketSessionEntity.collectionId].
  static final collectionId = obx.QueryStringProperty<WebSocketSessionEntity>(
    _entities[6].properties[2],
  );

  /// See [WebSocketSessionEntity.requestId].
  static final requestId = obx.QueryStringProperty<WebSocketSessionEntity>(
    _entities[6].properties[3],
  );

  /// See [WebSocketSessionEntity.url].
  static final url = obx.QueryStringProperty<WebSocketSessionEntity>(
    _entities[6].properties[4],
  );

  /// See [WebSocketSessionEntity.startTime].
  static final startTime = obx.QueryDateProperty<WebSocketSessionEntity>(
    _entities[6].properties[5],
  );

  /// See [WebSocketSessionEntity.endTime].
  static final endTime = obx.QueryDateProperty<WebSocketSessionEntity>(
    _entities[6].properties[6],
  );
}
